### PR TITLE
Build and deploy pdoc with gitnub action

### PR DESCRIPTION
**Pull request by kh31d4r**

### CODE REVIEW

**Comment by kh31d4r** [comment]
i kept the /pdoc suffix, but maybe it should be removed (or a nicer landing page created for the github-pages page)

**Comment by kh31d4r** [comment]
not sure why deploy is failing. it was failing with the same error for my own repo, but that was fixed by adding the permissions in the deploy job configuration

**Comment by mosbth** [comment]
> Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable

image

```yaml
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
```

https://stackoverflow.com/a/74167257/341137

**Comment by kh31d4r** [comment]
yeah, but I have
 ```
permissions:
  id-token: write
  pages: write
```

in the code, and the error is complaining about `id-token: write`. Which it did on my own repo also, before I added this code.

**Comment by kh31d4r** [comment]
Adding the read permission didn't help. Any chance you have been tinkering with the security settings for the repo? :)

**Comment by mosbth** [comment]
Ok, I'll check that later, it might be easier for me to test the deploy action.

**Pull request merged**
